export default defineEventHandler((event) => {
  return games;
});

const games = [
  {
    date: "1/3/2023",
    script: "Sects and Violets",
    location: "Online",
    initialCharacter: "No Dashii",
    alignment: "Evil",
    final3: true,
    win: true,
  },
  {
    date: "1/4/2023",
    script: "Bad Moon Rising",
    location: "Online",
    initialCharacter: "Gambler",
    alignment: "Good",
    final3: false,
    win: false,
  },
  {
    date: "1/10/2023",
    script: "The Ladder",
    location: "Online",
    initialCharacter: "Pukka",
    alignment: "Evil",
    final3: true,
    win: false,
  },
  {
    date: "1/11/2023",
    script: "The Ladder",
    location: "Online",
    initialCharacter: "Widow",
    alignment: "Evil",
    final3: null,
    win: false,
  },
  {
    date: "1/11/2023",
    script: "Trouble Brewing",
    location: "Online",
    initialCharacter: "Baron",
    alignment: "Evil",
    final3: true,
    win: true,
  },
  {
    date: "1/21/2023",
    script: "Trouble Brewing",
    location: "In Person",
    initialCharacter: "Poisoner",
    alignment: "Evil",
    final3: true,
    win: false,
  },
  {
    date: "1/24/2023",
    script: "Bad Moon Rising",
    location: "Online",
    initialCharacter: "Tinker",
    alignment: "Good",
    final3: false,
    win: false,
  },
  {
    date: "1/30/2023",
    script: "Trouble Brewing",
    location: "Online",
    initialCharacter: "Chef",
    alignment: "Good",
    final3: true,
    win: false,
  },
  {
    date: "1/30/2023",
    script: "Trouble Brewing",
    location: "Online",
    initialCharacter: "Slayer",
    alignment: "Good",
    final3: null,
    win: true,
  },
  {
    date: "2/3/2023",
    script: "Codependents Anonymous",
    location: "Online",
    initialCharacter: "Huntsman",
    alignment: "Good",
    final3: null,
    win: true,
  },
  {
    date: "2/6/2023",
    script: "Sects and Violets",
    location: "Online",
    initialCharacter: "Witch",
    alignment: "Evil",
    final3: true,
    win: true,
  },
  {
    date: "2/8/2023",
    script: "Sects and Violets",
    location: "Online",
    initialCharacter: "Snake Charmer",
    alignment: "Good",
    final3: true,
    win: false,
  },
  {
    date: "2/13/2023",
    script: "Trouble Brewing",
    location: "Online",
    initialCharacter: "Mayor",
    alignment: "Good",
    final3: false,
    win: true,
  },
  {
    date: "2/20/2023",
    script: "Trouble Brewing",
    location: "Online",
    initialCharacter: "Monk",
    alignment: "Good",
    final3: false,
    win: false,
  },
  {
    date: "2/20/2023",
    script: "Bad Moon Rising",
    location: "Online",
    initialCharacter: "Tea Lady",
    alignment: "Good",
    final3: false,
    win: false,
  },
  {
    date: "2/22/2023",
    script: "Fall of Rome",
    location: "Online",
    initialCharacter: "Augur",
    alignment: "Evil",
    final3: null,
    win: false,
  },
  {
    date: "2/22/2023",
    script: "Fall of Rome",
    location: "Online",
    initialCharacter: "Blacksmith",
    alignment: "Good",
    final3: null,
    win: false,
  },
  {
    date: "2/22/2023",
    script: "Fall of Rome",
    location: "Online",
    initialCharacter: "Hannibal",
    alignment: "Evil",
    final3: true,
    win: true,
  },
  {
    date: "2/27/2023",
    script: "Trouble Brewing",
    location: "Online",
    initialCharacter: "Undertaker",
    alignment: "Good",
    final3: null,
    win: true,
  },
  {
    date: "3/6/2023",
    script: "Trouble Brewing",
    location: "Online",
    initialCharacter: "Slayer",
    alignment: "Good",
    final3: false,
    win: true,
  },
  {
    date: "3/11/2023",
    script: "The Ladder",
    location: "In Person",
    initialCharacter: "Snake Charmer",
    alignment: "Good",
    final3: null,
    win: true,
  },
  {
    date: "3/11/2023",
    script: "The Ladder",
    location: "In Person",
    initialCharacter: "Snake Charmer",
    alignment: "Evil",
    final3: true,
    win: true,
  },
  {
    date: "3/26/2023",
    script: "Dance, Monkey, Dance",
    location: "Online",
    initialCharacter: "Juggler",
    alignment: "Good",
    final3: null,
    win: true,
  },
  {
    date: "4/10/2023",
    script: "Trouble Brewing",
    location: "Online",
    initialCharacter: "Empath",
    alignment: "Good",
    final3: false,
    win: true,
  },
  {
    date: "4/10/2023",
    script: "Sects and Violets",
    location: "Online",
    initialCharacter: "Vortox",
    alignment: "Evil",
    final3: null,
    win: false,
  },
  {
    date: "4/10/2023",
    script: "Sects and Violets",
    location: "Online",
    initialCharacter: "Dreamer",
    alignment: "Good",
    final3: true,
    win: true,
  },
  {
    date: "4/11/2023",
    script: "The Ladder",
    location: "Online",
    initialCharacter: "Lunatic",
    alignment: "Good",
    final3: false,
    win: false,
  },
  {
    date: "5/1/2023",
    script: "Trouble Brewing",
    location: "Online",
    initialCharacter: "Undertaker",
    alignment: "Good",
    final3: false,
    win: true,
  },
  {
    date: "5/2/2023",
    script: "Written Law",
    location: "Online",
    initialCharacter: "Al-Hadikhia",
    alignment: "Evil",
    final3: true,
    win: true,
  },
  {
    date: "5/2/2023",
    script: "Trouble Brewing",
    location: "Online",
    initialCharacter: "Washerwoman",
    alignment: "Good",
    final3: null,
    win: true,
  },
  {
    date: "5/15/2023",
    script: "???",
    location: "Online",
    initialCharacter: "Puzzlemaster",
    alignment: "Good",
    final3: null,
    win: true,
  },
  {
    date: "5/29/2023",
    script: "Violet Inns",
    location: "Online",
    initialCharacter: "Vizir",
    alignment: "Evil",
    final3: null,
    win: false,
  },
  {
    date: "5/29/2023",
    script: "Violet Inns",
    location: "Online",
    initialCharacter: "Minstrel",
    alignment: "Good",
    final3: null,
    win: false,
  },
  {
    date: "6/19/2023",
    script: "Trouble Brewing on Expert Mode",
    location: "Online",
    initialCharacter: "Legion",
    alignment: "Evil",
    final3: false,
    win: true,
  },
  {
    date: "6/26/2023",
    script: "Spirits of Ravenwood",
    location: "Online",
    initialCharacter: "Cannibal",
    alignment: "Good",
    final3: null,
    win: false,
  },
  {
    date: "6/26/2023",
    script: "Spirits of Ravenwood",
    location: "Online",
    initialCharacter: "Seamstress",
    alignment: "Good",
    final3: false,
    win: false,
  },
];
