# fly.toml app configuration file generated for clocktracker-discord on 2024-03-06T17:24:42-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'clocktracker-discord'
primary_region = 'lax'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
