import { GrimoireEventType } from "~/composables/useGames";

export type GrimoireReminderEventCadence =
  | "once"
  | "each_night"
  | "may_each_night"
  | "persistent";

export type GrimoireReminderTargetScope = "self" | "others" | "all";
export type GrimoireReminderSourceMode = "participant" | "npc";

export type GrimoireReminderEventConfig = {
  reminder: string;
  eventType: GrimoireEventType;
  cadence: GrimoireReminderEventCadence;
  sourceRoleIds: string[];
  sourceMode?: GrimoireReminderSourceMode;
  targetScope?: GrimoireReminderTargetScope;
  targetRoleIds?: string[];
};

// Reminder-to-event mapping used for automated status-event inference.
// Only strict, high-confidence mappings should be added here.
export const GRIMOIRE_REMINDER_EVENT_CONFIG: GrimoireReminderEventConfig[] = [
  {
    reminder: "Mad",
    eventType: GrimoireEventType.MAD,
    cadence: "each_night",
    sourceRoleIds: ["cerenovus", "harpy", "pixie"],
  },
  {
    reminder: "Drunk",
    eventType: GrimoireEventType.DRUNK,
    cadence: "each_night",
    sourceRoleIds: [
      "sailor",
      "innkeeper",
      "courtier",
      "philosopher",
      "sweetheart",
      "goon",
      "puzzlemaster",
      "organ_grinder",
      "village_idiot",
    ],
  },
  {
    reminder: "Poisoned",
    eventType: GrimoireEventType.POISONED,
    cadence: "each_night",
    sourceRoleIds: [
      "poisoner",
      "widow",
      "pukka",
      "no_dashii",
      "lleech",
      "vigormortis",
      "snake_charmer",
      "cannibal",
    ],
  },
  {
    reminder: "Lunch",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["cannibal"],
  },
  {
    reminder: "Abnormal",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["mathematician"],
  },
  {
    reminder: "Chosen",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["exorcist", "dreamer", "lunatic"],
  },
  {
    reminder: "Visit",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["high_priestess"],
  },
  {
    reminder: "Amigo",
    eventType: GrimoireEventType.OTHER,
    cadence: "persistent",
    sourceRoleIds: ["gnome"],
  },
  {
    reminder: "Chosen",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["nightwatchman"],
  },
  {
    reminder: "Chosen",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["ravenkeeper"],
  },
  {
    reminder: "Bounce",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["mayor"],
    targetScope: "self",
    targetRoleIds: ["mayor"],
  },
  {
    reminder: "No Ability",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["fisherman"],
  },
  {
    reminder: "No Ability",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["artist"],
    targetScope: "self",
    targetRoleIds: ["artist"],
  },
  {
    reminder: "No Ability",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["seamstress"],
    targetScope: "self",
    targetRoleIds: ["seamstress"],
  },
  {
    reminder: "Bingo",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["amnesiac"],
  },
  {
    reminder: "No Ability",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["fool"],
  },
  {
    reminder: "No Ability",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["huntsman"],
  },
  {
    reminder: "Saved",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["monk"],
  },
  {
    reminder: "Saved",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["pacifist"],
  },
  {
    reminder: "Saved",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["soldier"],
    targetScope: "self",
    targetRoleIds: ["soldier"],
  },
  {
    reminder: "Saved",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["sailor"],
    targetScope: "self",
    targetRoleIds: ["sailor"],
  },
  {
    reminder: "Saved",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["innkeeper"],
  },
  {
    reminder: "Saved",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["tea_lady"],
  },
  {
    reminder: "Saved",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["devils_advocate"],
  },
  {
    reminder: "Saved",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["deviant"],
  },
  {
    reminder: "No Ability",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["preacher"],
  },
  {
    reminder: "Correct",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["juggler"],
  },
  {
    reminder: "Guess Used",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["puzzlemaster"],
    targetScope: "self",
  },
  {
    reminder: "Evil Wakes",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["poppy_grower"],
    targetScope: "self",
    targetRoleIds: ["poppy_grower"],
  },
  {
    reminder: "Red Herring",
    eventType: GrimoireEventType.OTHER,
    cadence: "persistent",
    sourceRoleIds: ["fortune_teller"],
  },
  {
    reminder: "Yes",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["fortune_teller"],
  },
  {
    reminder: "Know",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["choirboy"],
  },
  {
    reminder: "Know",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["puzzlemaster"],
  },
  {
    reminder: "Outsider",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["librarian"],
  },
  {
    reminder: "Townsfolk",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["washerwoman"],
  },
  {
    reminder: "Minion",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["investigator"],
  },
  {
    reminder: "Know",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["steward", "balloonist", "noble"],
  },
  {
    reminder: "Died Today",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["undertaker"],
  },
  {
    reminder: "Doesn't Kill",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["princess"],
  },
  {
    reminder: "Master",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["butler"],
  },
  {
    reminder: "Claimed",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["goblin"],
  },
  {
    reminder: "Not in play",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["ojo"],
  },
  {
    reminder: "Registers as dead",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["zombuul"],
  },
  {
    reminder: "Storyteller Ability",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["plague_doctor"],
  },
  {
    reminder: "Swapped",
    eventType: GrimoireEventType.SEAT_CHANGE,
    cadence: "once",
    sourceRoleIds: ["matron"],
  },
  {
    reminder: "Dead",
    eventType: GrimoireEventType.DEATH,
    cadence: "once",
    sourceRoleIds: ["gunslinger"],
  },
  {
    reminder: "Dead",
    eventType: GrimoireEventType.DEATH,
    cadence: "once",
    sourceRoleIds: ["alchemist"],
    targetScope: "self",
    targetRoleIds: ["alchemist"],
  },
  {
    reminder: "Dead",
    eventType: GrimoireEventType.DEATH,
    cadence: "once",
    sourceRoleIds: ["tinker"],
    targetScope: "self",
    targetRoleIds: ["tinker"],
  },
  {
    reminder: "Dead",
    eventType: GrimoireEventType.DEATH,
    cadence: "once",
    sourceRoleIds: ["angel"],
    sourceMode: "npc",
  },
  {
    reminder: "Vote Given",
    eventType: GrimoireEventType.OTHER,
    cadence: "persistent",
    sourceRoleIds: ["beggar"],
  },
  {
    reminder: "3 Votes",
    eventType: GrimoireEventType.OTHER,
    cadence: "persistent",
    sourceRoleIds: ["bureaucrat"],
  },
  {
    reminder: "Negative Vote",
    eventType: GrimoireEventType.OTHER,
    cadence: "persistent",
    sourceRoleIds: ["thief"],
  },
  {
    reminder: "Acts Twice",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["barista"],
  },
  {
    reminder: "Sober and Healthy",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["barista"],
  },
  {
    reminder: "Executed",
    eventType: GrimoireEventType.EXECUTION,
    cadence: "once",
    sourceRoleIds: ["butcher"],
  },
  {
    reminder: "Execution Failed",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["judge"],
  },
  {
    reminder: "Executed",
    eventType: GrimoireEventType.EXECUTION,
    cadence: "once",
    sourceRoleIds: ["mutant"],
    targetScope: "self",
    targetRoleIds: ["mutant"],
  },
  {
    reminder: "Executed",
    eventType: GrimoireEventType.EXECUTION,
    cadence: "once",
    sourceRoleIds: ["scapegoat"],
    targetScope: "self",
    targetRoleIds: ["scapegoat"],
  },
  {
    reminder: "Executed",
    eventType: GrimoireEventType.EXECUTION,
    cadence: "once",
    sourceRoleIds: [],
  },
  {
    reminder: "Has Jumped",
    eventType: GrimoireEventType.DEATH,
    cadence: "once",
    sourceRoleIds: ["fang_gu"],
    targetScope: "self",
    targetRoleIds: ["fang_gu"],
  },
  {
    reminder: "Alive",
    eventType: GrimoireEventType.REVIVE,
    cadence: "once",
    sourceRoleIds: ["professor"],
  },
  {
    reminder: "Alive",
    eventType: GrimoireEventType.REVIVE,
    cadence: "once",
    sourceRoleIds: ["al-hadikhia"],
  },
  {
    reminder: "Alive",
    eventType: GrimoireEventType.REVIVE,
    cadence: "once",
    sourceRoleIds: ["shabaloth"],
  },
  {
    reminder: "Reincarnated",
    eventType: GrimoireEventType.REVIVE,
    cadence: "once",
    sourceRoleIds: ["hindu"],
    sourceMode: "npc",
  },
  {
    reminder: "Stormcaught",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["storm_catcher"],
    sourceMode: "npc",
  },
  {
    reminder: "Safe",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["storm_catcher"],
    sourceMode: "npc",
  },
  {
    reminder: "Has Ability",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["bone_collector"],
  },
  {
    reminder: "Has Ability",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["pixie"],
  },
  {
    reminder: "Has Ability",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["banshee"],
    targetScope: "self",
    targetRoleIds: ["banshee"],
  },
  {
    reminder: "Goal",
    eventType: GrimoireEventType.OTHER,
    cadence: "persistent",
    sourceRoleIds: ["zenomancer"],
    sourceMode: "npc",
  },
  {
    reminder: "Goal Completed",
    eventType: GrimoireEventType.OTHER,
    cadence: "once",
    sourceRoleIds: ["zenomancer"],
    sourceMode: "npc",
  },
  {
    reminder: "Is The Demon",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["lil_monsta"],
  },
  {
    reminder: "Is The Demon",
    eventType: GrimoireEventType.OTHER,
    cadence: "each_night",
    sourceRoleIds: ["scarlet_woman"],
    targetScope: "self",
    targetRoleIds: ["scarlet_woman"],
  },
  {
    reminder: "DEAD",
    eventType: GrimoireEventType.DEATH,
    cadence: "once",
    sourceRoleIds: ["big_wig"],
    sourceMode: "npc",
  },
  {
    reminder: "Dead",
    eventType: GrimoireEventType.DEATH,
    cadence: "once",
    sourceRoleIds: ["doomsayer"],
    sourceMode: "npc",
  },
  {
    reminder: "Dead",
    eventType: GrimoireEventType.DEATH,
    cadence: "once",
    sourceRoleIds: ["hells_librarian"],
    sourceMode: "npc",
  },
];
