name: deploy

on: push

jobs:
  fly:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --build-secret SUPABASE_URL=${{ secrets.SUPABASE_URL }} --build-secret SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
